{
    "name": "BackUpAlice",
    "version": "0.0.1",
    "icon": "fab fa-battle-net",
    "category": "undefined",
    "author": "LazzaAU",
    "maintainers": [],
    "desc": "Makes a backup copy of the projectalice folder",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        ""
    ],
    "conditions": {
        "lang": [
            "en"
        ],
        "online": true,
        "asrArbitraryCapture": true
    }
}